# Generated by Django 5.0.3 on 2024-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_developer_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
