# Generated by Django 5.0.3 on 2024-03-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_developer_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
