# Generated by Django 5.0.3 on 2024-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_alter_genre_genre_alter_publisher_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='description_short',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
