# Generated by Django 5.0.3 on 2024-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_games_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
