# Generated by Django 5.0.3 on 2024-03-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_games_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='app_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
