# Generated by Django 5.0.3 on 2024-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_category_app_id_alter_developer_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='developer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='publisher',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
