# Generated by Django 5.0.3 on 2024-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_games_category_games_developer_games_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
