# Generated by Django 5.0.3 on 2024-03-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_testpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPost',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='placeholder',
        ),
    ]
