# Generated by Django 5.0.3 on 2024-03-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_wishlistusergames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistUserGames',
        ),
    ]
