# Generated by Django 5.0.3 on 2024-03-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
