# Generated by Django 5.0.3 on 2024-03-25 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='game_app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.games', to_field='app_id'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
