# Generated by Django 5.0.3 on 2024-03-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_alter_wishlist_game_app_id_alter_wishlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='game_app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'app')},
        ),
    ]
