# Generated by Django 5.0.3 on 2024-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_rename_game_app_id_wishlist_app_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
