# Generated by Django 5.0.3 on 2024-03-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_cart_create_ts_cart_update_ts_customuser_create_ts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='create_ts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='update_ts',
        ),
    ]
