# Generated by Django 5.0.3 on 2024-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_remove_customuser_create_ts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='date_proper',
            field=models.DateField(null=True),
        ),
    ]
