# Generated by Django 5.0.3 on 2024-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0031_sale_games_date_proper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
