# Generated by Django 5.0.3 on 2024-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0033_remove_games_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='date_proper',
            new_name='release_date',
        ),
    ]
