# Generated by Django 5.0.3 on 2024-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0035_genre_salegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
