# Generated by Django 5.0.3 on 2024-04-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0036_genre_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salegenre',
            name='genre_id',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='SaleGenre',
        ),
    ]
