# Generated by Django 5.0.3 on 2024-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0040_rename_publishersale_salepublisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepublisher',
            name='sale_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salepublisher',
            name='sale_start_date',
            field=models.DateField(),
        ),
    ]
