# Generated by Django 5.0.3 on 2024-04-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0041_alter_salepublisher_sale_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalePublisher',
        ),
    ]
