# Generated by Django 5.0.3 on 2024-04-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0043_remove_publisher_games_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.games')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.publisher')),
            ],
            options={
                'unique_together': {('publisher', 'game')},
            },
        ),
    ]
