# Generated by Django 5.0.3 on 2024-04-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0045_remove_games_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.publisher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publishersale',
            constraint=models.CheckConstraint(check=models.Q(('sale_percent', 0), _negated=True), name='check_publisher_sale_percent'),
        ),
    ]
