# Generated by Django 5.0.3 on 2024-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0047_rename_publishersale_salepublisher'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salepublisher',
            name='check_publisher_sale_percent',
        ),
        migrations.AddConstraint(
            model_name='salepublisher',
            constraint=models.CheckConstraint(check=models.Q(('sale_percent__gt', 0), ('sale_percent__lt', 1)), name='check_publisher_sale_percent'),
        ),
    ]
