# Generated by Django 5.0.3 on 2024-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0048_remove_salepublisher_check_publisher_sale_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
