# Generated by Django 5.0.3 on 2024-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0049_publisher_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=10)),
                ('signal_triggered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
