# Generated by Django 5.0.3 on 2024-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0051_testsignalsinsert_rename_signalstest_testsignals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSignals',
        ),
        migrations.DeleteModel(
            name='TestSignalsInsert',
        ),
    ]
