# Generated by Django 5.0.3 on 2024-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0052_delete_testsignals_delete_testsignalsinsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=10)),
                ('signal_triggered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSignalsInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_field', models.CharField(max_length=100)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
