# Generated by Django 5.0.3 on 2024-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0053_testsignals_testsignalsinsert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsignals',
            old_name='signal',
            new_name='signal_text',
        ),
    ]
