# Generated by Django 5.0.3 on 2024-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0054_rename_signal_testsignals_signal_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsignals',
            name='signal_text',
            field=models.CharField(max_length=200),
        ),
    ]
