# Generated by Django 5.0.3 on 2024-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0055_alter_testsignals_signal_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSignals',
        ),
        migrations.DeleteModel(
            name='TestSignalsInsert',
        ),
        migrations.AddField(
            model_name='games',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
