# Generated by Django 5.0.3 on 2024-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0056_delete_testsignals_delete_testsignalsinsert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='on_sale',
        ),
    ]
