# Generated by Django 5.0.3 on 2024-04-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0058_category_categorygame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='CategoryGame',
            new_name='GenreGame',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='category',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genregame',
            old_name='category',
            new_name='genre',
        ),
        migrations.AlterUniqueTogether(
            name='genregame',
            unique_together={('genre', 'game')},
        ),
    ]
