# Generated by Django 5.0.3 on 2024-04-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0059_rename_category_genre_rename_categorygame_genregame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='genre',
        ),
    ]
