# Generated by Django 5.0.3 on 2024-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0060_remove_games_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPublishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_publisher', models.CharField(max_length=500)),
            ],
        ),
    ]
