# Generated by Django 5.0.3 on 2024-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0061_backuppublishers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupPublishers',
        ),
    ]
