# Generated by Django 5.0.3 on 2024-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0064_alter_reviews_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditReviewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
    ]
