# Generated by Django 5.0.3 on 2024-05-21 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0065_editreviewtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='editreviewtest',
            name='create_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
