# Generated by Django 5.0.3 on 2024-05-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0066_editreviewtest_create_ts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditReviewTest',
        ),
    ]
